### PR TITLE
fix initial selected

### PR DESCRIPTION
**Pull request by qinhuaihe**

### CODE REVIEW

**Comment by qinhuaihe** [comment]
These simply fixed #23, please take a look. However, there is another important shortage, the tree doesn't respond to outside selected items changing.

**Comment by qinhuaihe** [comment]
I noticed that the shortage was existed in the old version too. I think it's necessary to realize the feature.

**Comment by stefanloerwald** [comment]
I've taken a slightly different approach in fixing this, see #25. Please verify whether my changes are correct.

About changing the selection from the outside: This is because the `SelectedItems` are only looked at during first render. So that's why it can't be changed after the first render. I wonder what the use case for this is?

**Comment by qinhuaihe** [comment]
I will look it later, I am going out now. 
The reason is that we need to request the selected items from server sometimes, so we need to update it after first render.

**Comment by stefanloerwald** [comment]
A `@key` on the tree view could help: If you update the key after replacing the list of selected items, the entire tree view will be replaced.

**Comment by qinhuaihe** [comment]
By the way, since we both created pull requests, how can I fetch your code locally? I am a rookie😅.

**Comment by qinhuaihe** [comment]
> A `@key` on the tree view could help: If you update the key after replacing the list of selected items, the entire tree view will be replaced.

Ok, I will try. Thank you.

**Comment by stefanloerwald** [comment]
> By the way, since we both created pull requests, how can I fetch your code locally? I am a rookie😅.

I can recommend using the github CLI. In the top right of the PR, you'll find "Open with". If you have the GH CLI installed, you simply execute `gh pr checkout 24` to fetch & checkout this PR.

image

**Comment by qinhuaihe** [comment]
> A `@key` on the tree view could help: If you update the key after replacing the list of selected items, the entire tree view will be replaced.

```
@page "/selection"
<SourceCodeLink Repository="Blazor.TreeViews" Page="@nameof(Selection)" />

<TreeView @key="SelectedValues" Items="Items" GetParent="GetParent" AllowSelection="true" @bind-SelectedItems="SelectedValues" />

@if (SelectedValues != null)
{
    @string.Join(", ", SelectedValues)
}
<div>
    <button @onclick="@(() =>SelectedValues = new List<string> { })">
        Set nothing Selected
    </button>
    <button @onclick="@(() => SelectedValues = new List<string> { "3" })">
        Set 3 Selected
    </button>
    <button @onclick="@(() => SelectedValues = new List<string> { "3.1" })">
        Set 3.1 Selected
    </button>
    <button @onclick="@(() => SelectedValues = new List<string> { "3.1.1" })">
        Set 3.1.1 Selected
    </button>
</div>
...
```

I tried using @key to refresh the tree. But there are something strange. If any tree nodes selected, resetting key will lead tree nodes all unselected.
a

**Pull request closed without merging**
