### PR TITLE
fixed #23

### LINKED ISSUE #23: initial selected broken
I found my code made the initial selected broken . Initially setting `3.1.1` selected makes the whole `3` branch selected. I'm wondering how to fix it now.
image

### PR DESCRIPTION
**Pull request by stefanloerwald**
@qinhuaihe Please check out this PR and see whether it correctly fixes your issue #23.

### CODE REVIEW

**Comment by qinhuaihe** [comment]
There should be no problem this time. Good job! I will close mine.

**Comment by stefanloerwald** [comment]
> > A `@key` on the tree view could help: If you update the key after replacing the list of selected items, the entire tree view will be replaced.
> 
> ```
> @page "/selection"
> <SourceCodeLink Repository="Blazor.TreeViews" Page="@nameof(Selection)" />
> 
> <TreeView @key="SelectedValues" Items="Items" GetParent="GetParent" AllowSelection="true" @bind-SelectedItems="SelectedValues" />
> 
> @if (SelectedValues != null)
> {
>     @string.Join(", ", SelectedValues)
> }
> <div>
>     <button @onclick="@(() =>SelectedValues = new List<string> { })">
>         Set nothing Selected
>     </button>
>     <button @onclick="@(() => SelectedValues = new List<string> { "3" })">
>         Set 3 Selected
>     </button>
>     <button @onclick="@(() => SelectedValues = new List<string> { "3.1" })">
>         Set 3.1 Selected
>     </button>
>     <button @onclick="@(() => SelectedValues = new List<string> { "3.1.1" })">
>         Set 3.1.1 Selected
>     </button>
> </div>
> ...
> ```
> 
> I tried using @key to refresh the tree. But there are something strange. If any tree nodes selected, resetting key will lead tree nodes all unselected.
> a


Thanks for your comment over in #24. I was able to reproduce this issue and found the solution: In the dispose method of `ListItem` we had a call to `SelectionChanged`. It's important to consider what happens when the item collection of a tree view changes, because removing an item from a tree view has various consequences (different tree layout, different selection state).

Turns out, it's wrong to "change" the selection when an item is removed. It's just necessary to re-evaluate its parent's selected state after removing the child-relationship from that parent: https://github.com/excubo-ag/Blazor.TreeViews/pull/25/commits/5af3df24794a53101f5d7bd3e1211fb9fb4077ce

**Comment by qinhuaihe** [comment]
Thank you! But clicking the set buttons cannot change the tree selection now.

**Comment by stefanloerwald** [comment]
Strange! It worked for me locally, but not in the wasm demo. I'll have another look. Sorry about this.

**Comment by stefanloerwald** [comment]
I think I was able to fix this: There was too much happening on disposed list items. v2.1.1 is in deployment.

**Comment by qinhuaihe** [comment]
Thank you again! That is quite helpful.

**Pull request merged**
