### PR TITLE
Lazy loading for GetChildren

### PR DESCRIPTION
**Pull request by fhayd**
This feature gives the tree the ability to lazily load children elements for very large trees.

This change the GetChildren behaviour to populate the Tree only when user open an item.
This changes implies two things:

- Add a parameter `HasChildren` to `TreeView` that is used to know if an item has any children without using `GetChildren`. This take any `Func<T, bool>` function.
- If `HasChildren` is defined, always collapse all items, else it won't be lazy.

If the parameter `HasChildren` is not defined, the tree should have the same behaviour as before.
Note that one should define `HasChildren` AND `GetChildren` to enable the lazy loading (i.e. it is impossible to lazy load items with `GetParent`)

### CODE REVIEW

**Comment by stefanloerwald** [comment]
Thanks for your contribution, @fhayd! Very cool indeed :-)

I would like to change some minor things before merging. Could you please give me rights to do so?

Thanks
Stefan

**Comment by fhayd** [comment]
Thanks for the feedback @stefanloerwald !
I can't find the option to gives you right to commit, don't you already have it ?

**Comment by stefanloerwald** [comment]
Could you please check whether you see this checkbox?

image

Maybe it's visible when you edit the PR. As an alternative, you could add me to the ArxOne/Blazor.TreeViews. Then I could push to that?

**Comment by fhayd** [comment]
That's what I was looking for but couln't :)
I added you to ArxOne/Blazor.TreeView. Tell me if you need anything else

**Review by stefanloerwald — APPROVED** [review]

**Comment by stefanloerwald** [comment]
Thank you for this contribution! I have just published the new version with this feature.

**Pull request merged**
