### PR TITLE
add disabled parameter

### LINKED ISSUE #21: support disabled parameter
I think  it's necessary to add `disabled` parameter. And also we need to be accessible to `disabled` value in custom checkbox render func.

### PR DESCRIPTION
**Pull request by qinhuaihe**
#21

### CODE REVIEW

**Comment by stefanloerwald** [comment]
Thanks for suggesting this and starting the work on this!

Disabling the entire tree view is one use case, but surely disabling just some of the items is also a use case, isn't it?

This requires some thought and proper testing:

- When an item is disabled, what happens to the selection state when a parent element's state is toggled?
- An item being disabled should also make all its children disabled.
- There's probably more...

Do you agree that this should be added too?

**Comment by qinhuaihe** [comment]
Yes, I agree. Maybe we can add a `Disable` component just like `Collapse`.

**Comment by qinhuaihe** [comment]
And furthermore, I don't know whether it is proper to disable the collapse functionality when the tree is disabled.

**Comment by stefanloerwald** [comment]
> And furthermore, I don't know whether it is proper to disable the collapse functionality when the tree is disabled.

Great question! I think that's depending on whether an item is disabled or the entire tree view. When the tree view is entirely disabled, I would expect not to be able to interact with it in any way. So in that case I wouldn't allow changing the collapse state. What do you think?

For items, it boils down to the question whether disabled only applies to the ability to select/deselect or to the item as a whole.

**Comment by qinhuaihe** [comment]
Sorry for the delay of my vacation. Please take a look. I tried to add a `Disable` component but failed. Instead I add `ItemDisabled` parameter to the tree.

**Comment by stefanloerwald** [comment]
Hi @qinhuaihe,

I hope you enjoyed your vacation!

I just tested the branch, and I found some behavior which isn't quite correct:

1. Start with page `/disable`
2. Toggle disable state of 1, such that 1, 1.1, and 1.2 become enabled.
3. Toggle disable state of 1.1, such that 1.1 becomes disabled.
4. Select 1.2 As a result 1 Is now checked, but should only be indeterminate. (Alternative: select 1 here, for the same effect).
5. Toggle disable state of 1.1, such that 1.1 becomes enabled.
6. Now the invalid state is even more apparent: 1 is checked, suggesting that 1.1, and 1.2 should be checked too, but 1.1 isn't.

This has an interesting effect: when a subitem is disabled and not selected, selecting the parent will not result in the parent to be checked, but only indeterminate.

Would you mind looking into this?

Thanks
Stefan

**Comment by qinhuaihe** [comment]
Thank you. 
If we don't ignore the check status of disabled tree nodes, there will be some complicated situations.
image
image

For example, what to do when clicked the checkbox of tree node 1? It's not easy to deal with. Can you give me some advice?

**Comment by qinhuaihe** [comment]
I have pushed the buggy code for your convenience to look.

**Comment by stefanloerwald** [comment]
Thanks for pushing the code. It is indeed still buggy, but I think we can get where we need to be. I think the current way of dealing with indeterminate is wrong. I hope we can fix that without changing the `Selected` property of `ListItem<T>`.

I think the important bit to realize is that a checkbox isn't just tristate (unchecked, indeterminate, checked), but has four states:
It is either **d**eterminate or **i**ndeterminate and either **c**hecked or **u**nchecked. So we have the four states dc, du, ic, iu.

You can verify that with four checkboxes:
image
Pressing each once results in 
image
So even though the third and fourth checkbox look identical, they are not.

Clicking a checkbox always toggles the c/u state, and may toggle the d/i state, but in a treeview that depends on the children.

| Situation | Action | Expected | Explanation |
| --- | --- | --- | --- |
| image | Click 1 |  image | 1 changes from u/d to c/i, 1.1 and 1.3 change from u/d to c/d
| image | Click 1.1 | image | 1 changes from u/d to u/i, 1.1 from u/d to c/d
|  image with 1 u/i | Click 1 |  image | 1 changes from u/i to c/i, 1.1 stays at c/d and 1.3 changes from u/d to c/d
|  image with 1 c/i | Click 1 |  image | 1 changes from c/i to u/d, 1.1 changes from c/d to u/d
|  image with 1 u/i | Click 1.1 |  image  | 1 changes from u/i to u/d, 1.1 changes from c/d to u/d
|  image with 1 c/i | Click 1.1 |  image | 1 changes from c/i to u/d, 1.1 changes from c/d to u/d
|  image with 1 u/i | Click 1.3 |   image  | 1.3 changes from u/d to c/d
|  image with 1 c/i | Click 1.3 |   image |  1.3 changes from u/d to c/d
|  image with 1 u/i | Click 1 |  image | 1 changes from u/i to c/i
|  image with 1 c/i | Click 1 |  image | 1 changes from c/i to u/d, 1.1 changes from c/d to u/d, 1.3 changes from c/d to u/d
| image with 1 u/i | Click 1.2 | image | 1 changes from u/i to c/d, 1.2 changes from u/d to c/d
| image with 1 c/i | Click 1.2 | image | 1 changes from c/i to c/d, 1.2 changes from u/d to c/d
| image with 1 u/i | Click 1 | image | 1 changes from u/i to c/d, 1.2 changes from u/d to c/d
| image with 1 c/i | Click 1 | image | 1 changes from c/i to u/d, 1.1 and 1.3 change from c/d to u/d
| image | Click 1 | image | 1 changes from c/d to u/i, 1.1 and 1.3 change from c/d to u/d
| image with 1 u/i | Click 1 | image | 1 changes from u/i to c/i, 1.3 changes from u/d to c/d
| image with 1 c/i | Click 1 | image | 1 changes from c/i to u/i

This is not an exhaustive list of all possible changes, but I hope it is fully logical. There's no way for the user to distinguish between c/i and u/i, but that's just a limitation of checkboxes.

**Comment by qinhuaihe** [comment]
I'm almost there. But there are still some issues:

1. I don't know how to pass indeterminate state to MatBlazor Checkbox, The checkbox requires value's type to be `bool?` to enable indeterminate,  it seems not compatible.
2. Is it necessary to pass indeterminate change callback to checkbox ?

**Comment by stefanloerwald** [comment]
> 1. I don't know how to pass indeterminate state to MatBlazor Checkbox, The checkbox requires value's type to be `bool?` to enable indeterminate,  it seems not compatible.

I'm not surprised. `MatBlazor` doesn't implement indeterminate checkboxes correctly, because they went for tristate and checkboxes just aren't (which is probably surprising to many, yet perfectly logical). We still have to at least try to get it right...

> 2. Is it necessary to pass indeterminate change callback to checkbox ?

I haven't tested what happens if we leave it out. I'll investigate.

Thanks for your effort on this!

**Comment by stefanloerwald** [comment]
From what I can see, the behavior with the default checkboxes is now 100% correct. Well done!

**Comment by stefanloerwald** [comment]
I think I fixed the MatBlazor code. Could you please verify if all is correct? If so, I'll merge and release a new version.

Thanks
Stefan

**Comment by qinhuaihe** [comment]
Yes, it does work, good job.
One more thing else, please look at [CheckboxFragment](https://github.com/excubo-ag/Blazor.TreeViews/pull/22/files#diff-b80ffbbd63e26f7a697df9fc9c76e02fe3c7c330bc32e1aa2a0c37048afe875eR16). Since the `indeterminate_change` method does nothing, `CheckboxFragment` and `CheckboxFragment2` are exactly the same thing now. Would you consider to simplify it?

**Comment by stefanloerwald** [comment]
Done! Thanks again for the effort you put into this. It's a really valuable addition to this library. I decided to mark this as a major version increase, as the changes to `CheckboxFragment` were quite substantial.

The workflow to deploy to nuget ran successfully, so V2.0.0 should become available in a few minutes.

**Comment by qinhuaihe** [comment]
Thank you very much for your effort and patience. It's a pleasure to collaborate with you.😁

**Pull request merged**
